# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

## default
# version: 2
# updates:
#   - package-ecosystem: "" # See documentation for possible values
#     directory: "/" # Location of package manifests
#     schedule:
#       interval: "weekly"
## end

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    groups:
      pip:
        applies-to: "security-updates"
        patterns:
          - "*"
