apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: monitoring
  labels:
    app: zabbix-server
spec:
  type: ClusterIP
  selector:
    app: zabbix-server
  ports:
    - name: zabbix-trapper
      port: 10051
      targetPort: 10051
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: monitoring
  labels:
    app: zabbix-web
spec:
  type: LoadBalancer   # or ClusterIP + Ingress
  selector:
    app: zabbix-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
